/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package mx.edu.itses.progadv.proyectofinal.mvc.views.empleado;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;
import mx.edu.itses.progadv.proyectofinal.mvc.controllers.EmpleadoController;
import mx.edu.itses.progadv.proyectofinal.mvc.models.Empleado;

/**
 *
 * @author Administrador
 */
public class CRUDEmpleado extends javax.swing.JFrame {

    private static DefaultTableModel tabla;
    private int renglon;

    /**
     * Creates new form CRUDEmpleado
     *
     * @param model
     */
    public CRUDEmpleado(Empleado model) {
        initComponents();

        tabla = (DefaultTableModel) tblEmpleados.getModel();

        /*tabla.addRow(new Object[]{"1","Iván","Tovar B","IT"});
        tabla.addRow(new Object[]{"2","Juan","Pérez","Ingeniería"});
        tabla.addRow(new Object[]{"3","Karla","Alvarez","Finanzas"});
        
        System.out.println(tabla.getRowCount());
        
        tabla.setValueAt("Pedro", 1, 1);
        
        tabla.removeRow(2);*/
        setLocationRelativeTo(null);
        btnCreate.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                EmpleadoController.createEmpleado();
            }

        });

        btnRead.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                EmpleadoController.readEmpleado();
            }

        });

        btnUpdate.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                EmpleadoController.updateEmpleado();
            }

        });
        btnDelete.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                EmpleadoController.deleteEmpleado();
            }

        });
        //IMPORTANTE
        // CUANDO SE CREA POR PRIMERA VEZ EL FORMULARIO HAY QUE INVOCAR EL MÉTODO INDEX DESDE ESTE PUNTO
        SwingUtilities.invokeLater(() -> {
            // LLENA LOS DATOS DE LOS EMPLEADOS
            EmpleadoController.index();
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jplBotones = new javax.swing.JPanel();
        btnCreate = new javax.swing.JButton();
        btnRead = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        jplTitulo = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        pnlIndex = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblEmpleados = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        btnCreate.setText("Create");
        jplBotones.add(btnCreate);

        btnRead.setText("Read");
        jplBotones.add(btnRead);

        btnUpdate.setText("Update");
        jplBotones.add(btnUpdate);

        btnDelete.setText("Delete");
        jplBotones.add(btnDelete);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("CRUD de modelo Empleado");
        jplTitulo.add(jLabel1);

        tblEmpleados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "#", "Nombre", "Apellidos", "Departamento"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblEmpleados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tblEmpleadosMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(tblEmpleados);

        javax.swing.GroupLayout pnlIndexLayout = new javax.swing.GroupLayout(pnlIndex);
        pnlIndex.setLayout(pnlIndexLayout);
        pnlIndexLayout.setHorizontalGroup(
            pnlIndexLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlIndexLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlIndexLayout.setVerticalGroup(
            pnlIndexLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlIndexLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jplBotones, javax.swing.GroupLayout.DEFAULT_SIZE, 438, Short.MAX_VALUE)
            .addComponent(jplTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlIndex, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jplTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(jplBotones, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlIndex, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblEmpleadosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblEmpleadosMousePressed
        // TODO add your handling code here:

        JTable tabla = (JTable) evt.getSource();
        renglon = tabla.rowAtPoint(evt.getPoint());
        if (evt.getClickCount() == 2) {
            renglon = tabla.rowAtPoint(evt.getPoint());
        }
        System.out.println(renglon);

    }//GEN-LAST:event_tblEmpleadosMousePressed

    public void updateTabla(List<Empleado> empleados) {

        for (int i = CRUDEmpleado.tabla.getRowCount() - 1; i >= 0; i--) {
            CRUDEmpleado.tabla.removeRow(i);
        }

        empleados.forEach(model -> {
            CRUDEmpleado.tabla.addRow(new Object[]{model.getId(), model.getNombre(), model.getApellidos(), model.getDepartamento()});
        });
    }

    public String getTableRow() {
        return CRUDEmpleado.tabla.getValueAt(renglon, 0).toString();
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCreate;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnRead;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel jplBotones;
    private javax.swing.JPanel jplTitulo;
    private javax.swing.JPanel pnlIndex;
    private javax.swing.JTable tblEmpleados;
    // End of variables declaration//GEN-END:variables
}
