/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package mx.edu.itses.progadv.proyectofinal.mvc.views.libro;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import mx.edu.itses.progadv.proyectofinal.mvc.controllers.LibroController;
import mx.edu.itses.progadv.proyectofinal.mvc.models.Libro;

/**
 *
 * @author Administrador
 */
public class CRUDLibro extends javax.swing.JFrame {

    private static DefaultTableModel tabla;
    private int renglon;
    /**
     * Creates new form CRUDLibro
     *
     */
    public CRUDLibro() {
        initComponents();

       
        setLocationRelativeTo(null);
        btnCreate.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
               LibroController.createLibro();
            }

        });

        btnRead.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                LibroController.readLibro();
            }

        });

        btnUpdate.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                LibroController.updateLibro();
            }

        });
        btnDelete.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                LibroController.deleteLibro();
            }

        });

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jplBotones = new javax.swing.JPanel();
        btnCreate = new javax.swing.JButton();
        btnRead = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        jplTitulo = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnCreate.setText("Create");
        jplBotones.add(btnCreate);

        btnRead.setText("Read");
        jplBotones.add(btnRead);

        btnUpdate.setText("Update");
        jplBotones.add(btnUpdate);

        btnDelete.setText("Delete");
        jplBotones.add(btnDelete);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("CRUD de modelo Libro");
        jplTitulo.add(jLabel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jplBotones, javax.swing.GroupLayout.DEFAULT_SIZE, 438, Short.MAX_VALUE)
            .addComponent(jplTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jplTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(jplBotones, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(370, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    
    /*public void updateTabla(Libro model){
        int row = CRUDLibro.tabla.getRowCount();
        CRUDLibro.tabla.addRow(new Object[]{row+1,model.getNombre(),model.getApellidos(),model.getDepartamento()});
    }
    
    
    public void getTableRow(Libro model){
        model.setNombre(CRUDLibro.tabla.getValueAt(renglon, 1).toString());
        model.setApellidos(CRUDLibro.tabla.getValueAt(renglon, 2).toString());
        model.setDepartamento(CRUDLibro.tabla.getValueAt(renglon, 3).toString());
    }*/
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCreate;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnRead;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jplBotones;
    private javax.swing.JPanel jplTitulo;
    // End of variables declaration//GEN-END:variables
}
